image: php:7.4.2

before_script:
    - bash ci/docker_install.sh > /dev/null

test:app:
    script:
        - php composer.phar install
        - php vendor/bin/phpunit --log-junit report.xml tests
    artifacts:
        reports:
            junit: report.xml
